apiVersion: v1
kind: ServiceAccount
metadata:
  name: vtm-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vtm-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vtm-user
subjects:
- kind: ServiceAccount
  name: vtm-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: vtm-user
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - nodes
  - pods
  verbs:
  - get
  - list